trigger:
  batch: true
  branches:
    include:
    - main
    - release/6.0
    - release/7.0
    - release/8.0
  paths:
    include:
      - '*'
    exclude:
      - .github/*
      - Documentation/*
      - Images/*
      - CODE-OF-CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE.TXT
      - PATENTS.TXT
      - README.md
      - SECURITY.md
      - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - release/6.0
    - release/7.0
    - release/8.0
    - templates
  paths:
    include:
      - '*'
    exclude:
      - .github/*
      - Documentation/*
      - Images/*
      - CODE-OF-CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE.TXT
      - PATENTS.TXT
      - README.md
      - SECURITY.md
      - THIRD-PARTY-NOTICES.TXT


variables:
- template: /eng/common-variables.yml
- template: /eng/common/templates/variables/pool-providers.yml

resources:
  containers:
  - container: LinuxContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-fpm

stages:
- template: azure-pipelines.template.yml