# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
parameters:
  jobNamePrefix: 'Source_Build'
  platform: {}
jobs:
- job: ${{ parameters.jobNamePrefix }}_${{ parameters.platform.name }}
  displayName: Source-Build (${{ parameters.platform.name }})
  ${{ each property in parameters.platform.jobProperties }}:
    ${{ property.key }}: ${{ property.value }}
  ${{ if ne(parameters.platform.container, '') }}:
    container: ${{ parameters.platform.container }}
  ${{ if eq(parameters.platform.pool, '') }}:
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: $[replace(replace(eq(contains(coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranch'], 'refs/heads/main'), 'release'), 'true'), True, 'NetCore-Svc-Public' ), False, 'NetCore-Public')]
        demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: $[replace(replace(eq(contains(coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranch'], 'refs/heads/main'), 'release'), 'true'), True, 'NetCore1ESPool-Svc-Internal'), False, 'NetCore1ESPool-Internal')]
        demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  ${{ if ne(parameters.platform.pool, '') }}:
    pool: ${{ parameters.platform.pool }}
  workspace:
    clean: all

  steps:
  - template: /eng/common/templates/steps/source-build.yml@self
    parameters:
      platform: ${{ parameters.platform }}
  - template: /eng/common/templates/steps/Arcade.PublishPipelineArtifact.yml@self
    parameters:
      displayName: 'Publish BuildLogs'
      mainCondition: succeededOrFailed()
      targetPath: '$(Build.StagingDirectory)/BuildLogs'
      artifactName: BuildLogs_SourceBuild_${{ parameters.platform.name }}_Attempt$(System.JobAttempt)
      runAsInternal: ${{ ne(variables['System.TeamProject'], 'public') }}