stages:
- template: /eng/common/core-templates/post-build/post-build.yml
  parameters:
    # Specifies whether to use 1ES
    templateIs1ESManaged: false

    ${{ each parameter in parameters }}:
      ${{ parameter.key }}: ${{ parameter.value }}